#!/usr/bin/env bash
#
# Re-install the ECC operator layer under .claude/ from a pinned upstream ref.
#
# Everything in .claude/ except launch.json is generated by this script, so the
# way to change what ECC ships here is to edit ecc-install.json and re-run it —
# not to hand-edit files under .claude/.
#
#   bash scripts/ecc/sync.sh              # reinstall at the pinned ref
#   ECC_REF=main bash scripts/ecc/sync.sh # try a newer upstream revision
#
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CONFIG="$PROJECT_DIR/ecc-install.json"
ECC_REPO_URL="${ECC_REPO_URL:-https://github.com/affaan-m/ecc.git}"
ECC_REF="${ECC_REF:-$(node -p "require('$CONFIG').options.eccRef")}"
SKILLS="$(node -p "require('$CONFIG').options.skills.join(',')")"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "[ecc] cloning $ECC_REPO_URL @ $ECC_REF"
git clone --depth 1 --branch "$ECC_REF" "$ECC_REPO_URL" "$WORK/ecc" >/dev/null 2>&1

echo "[ecc] installing installer dependencies"
(cd "$WORK/ecc" && npm install --no-audit --no-fund --loglevel=error >/dev/null)

cd "$PROJECT_DIR"
echo "[ecc] applying $CONFIG"
node "$WORK/ecc/scripts/install-apply.js" --config "$CONFIG"

echo "[ecc] adding repo-specific skills: $SKILLS"
node "$WORK/ecc/scripts/install-apply.js" --target claude-project --skills "$SKILLS"

# ECC's hook scripts are CommonJS, and this project's package.json sets
# "type": "module", which would otherwise make Node parse them as ESM and fail
# on their first require(). Scope them back to CommonJS.
cat > "$PROJECT_DIR/.claude/scripts/package.json" <<'JSON'
{
  "name": "ecc-project-hook-scripts",
  "private": true,
  "type": "commonjs"
}
JSON

node "$PROJECT_DIR/scripts/ecc/wire-settings.mjs"

echo "[ecc] done. Review 'git status' before committing."
