/**
 * Generates `src/range/preflopStrength.ts`.
 *
 * Hand strength is DERIVED from this project's own equity engine — the
 * all-in equity of each of the 169 starting-hand classes against one random
 * opponent — rather than copied from a published chart. That keeps a single
 * source of truth: if the evaluator is ever wrong, the ranges built on it are
 * wrong in the same direction, and the engine's own tests catch it.
 *
 * Suits are interchangeable before the board arrives, so one representative
 * combination per class is sufficient.
 *
 *   npx tsx tools/generate-preflop-strength.ts
 */

import { writeFileSync } from 'node:fs';
import { Card, makeCard, Suit } from '../src/engine/card';
import { computeEquity } from '../src/engine/equity';
import { GameState } from '../src/engine/gameState';
import { allClassKeys } from '../src/range/combos';

const SAMPLES = 120_000;
const LABEL_TO_RANK: Record<string, number> = {
  '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9,
  '10': 10, J: 11, Q: 12, K: 13, A: 14,
};

/** One representative holding for a class key such as "AKs" or "QQ". */
function representative(key: string): Card[] {
  const suited = key.endsWith('s');
  const offsuit = key.endsWith('o');
  const ranksPart = suited || offsuit ? key.slice(0, -1) : key;

  // Ranks are single characters except "10".
  const labels = ranksPart.startsWith('10')
    ? ['10', ranksPart.slice(2)]
    : ranksPart.endsWith('10')
      ? [ranksPart.slice(0, -2), '10']
      : [ranksPart[0]!, ranksPart[1]!];

  const high = LABEL_TO_RANK[labels[0]!]!;
  const low = LABEL_TO_RANK[labels[1]!]!;
  const secondSuit: Suit = suited ? 's' : 'h';
  return [makeCard(high, 's'), makeCard(low, high === low ? 'h' : secondSuit)];
}

function main(): void {
  const keys = allClassKeys();
  const results: { key: string; equity: number }[] = [];
  const started = Date.now();

  for (const [index, key] of keys.entries()) {
    const state: GameState = {
      variant: 'texas',
      totalPlayers: 2,
      activePlayers: 2,
      hole: representative(key),
      board: [],
    };
    const equity = computeEquity(state, {
      mode: 'monteCarlo',
      minSamples: SAMPLES,
      maxSamples: SAMPLES,
      // Fixed seed: regenerating must reproduce the table exactly.
      seed: 20260825,
    });
    results.push({ key, equity: equity.equity });
    if ((index + 1) % 20 === 0) {
      process.stderr.write(`  ${index + 1}/${keys.length} (${Date.now() - started}ms)\n`);
    }
  }

  results.sort((a, b) => b.equity - a.equity);

  const rows = results
    .map(({ key, equity }) => `  ['${key}', ${equity.toFixed(5)}],`)
    .join('\n');

  const file = `/**
 * Starting-hand strength: the 169 classes ordered by all-in equity against one
 * random opponent, strongest first.
 *
 * GENERATED by tools/generate-preflop-strength.ts from this project's own
 * equity engine (${SAMPLES.toLocaleString('en-US')} Monte-Carlo samples per class, fixed seed).
 * Do not edit by hand — regenerate.
 *
 * Equity against a random hand is a defensible ordering, not a perfect one: it
 * takes no account of playability, position or how a hand fares multiway. It is
 * used to define "the top X% of hands", which is all a range model needs.
 */

/** [class key, equity vs one random hand], strongest first. */
export const PREFLOP_STRENGTH: readonly (readonly [string, number])[] = [
${rows}
];
`;

  writeFileSync('src/range/preflopStrength.ts', file);
  process.stderr.write(`Wrote ${results.length} classes in ${Date.now() - started}ms\n`);
}

main();
